server:
  port: 8085

core:
  meta:
    datasource:
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: KDADMIN
      password: admin12345
      driver-class-name: oracle.jdbc.OracleDriver

  session:
    store-type: jdbc
